[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet publish SkladBlazorApp.Server/SkladBlazorApp.Server.csproj -c Release -o out"]

[start]
cmd = "dotnet out/SkladBlazorApp.Server.dll"